version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    environment:
      CONFIG: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql://demouser:demopass@pg:5433/blog
    ports:
      - "8000:80"
    depends_on:public
      pg:
        condition: service_healthy

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
       - "5433:5432"
 #      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
